import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Data Processing Agreement',
  description: 'Data Processing Agreement (GDPR Art. 28) for GameOn business customers.',
};

export default function DpaPage() {
  return (
    <div style={{ background: '#0D1520', minHeight: '100vh', color: '#DCE4EE', fontFamily: "'Sora', sans-serif" }}>

      {/* Nav */}
      <nav style={{ borderBottom: '1px solid rgba(124,189,212,0.1)', padding: '0 40px' }}>
        <div style={{ maxWidth: 1100, margin: '0 auto', height: 68, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
            <div style={{ width: 32, height: 32, borderRadius: 9, background: 'linear-gradient(135deg,#7CBDD4,#4890aa)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#0D1520" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 3v7"/><path d="M7.2 6.2A8 8 0 1 0 16.8 6.2"/>
              </svg>
            </div>
            <span style={{ fontSize: 18, fontWeight: 800, letterSpacing: '-0.03em', color: '#DCE4EE' }}>
              Game<span style={{ color: '#7CBDD4' }}>On</span>
            </span>
          </Link>
          <Link href="/" style={{ fontSize: 13, fontWeight: 600, color: '#8FA8C0', textDecoration: 'none' }}>
            ← Back
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: 760, margin: '0 auto', padding: '72px 40px 120px' }}>

        <p style={{ fontSize: 12, fontWeight: 700, letterSpacing: '0.2em', textTransform: 'uppercase', color: '#7CBDD4', marginBottom: 16 }}>
          Legal
        </p>
        <h1 style={{ fontSize: 'clamp(32px,5vw,48px)', fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 12, lineHeight: 1.1 }}>
          Data Processing Agreement
        </h1>
        <p style={{ fontSize: 14, color: '#4A6580', marginBottom: 56 }}>
          Last updated: July 6, 2026
        </p>

        <Section title="1. Parties and Scope">
          <P>This Data Processing Agreement ("DPA") forms part of the <Link href="/terms" style={{ color: '#7CBDD4', textDecoration: 'underline', textUnderlineOffset: 3 }}>Terms of Service</Link> between GameOn ("Processor", "we") and the business customer holding the account ("Controller", "you"). It applies automatically whenever you use GameOn to run games in which your employees, colleagues or event participants ("players") take part, and governs our processing of players&apos; personal data on your behalf under Article 28 GDPR.</P>
          <P style={{ marginTop: 12 }}>For your own account data (your email, login and billing details) we act as an independent controller — that processing is described in our <Link href="/privacy" style={{ color: '#7CBDD4', textDecoration: 'underline', textUnderlineOffset: 3 }}>Privacy Policy</Link>.</P>
        </Section>

        <Section title="2. Subject Matter, Nature and Purpose">
          <P>We process player personal data solely to provide the GameOn service: letting players join games, play missions, submit answers and photos, appear on leaderboards, and generating result reports for you. Processing lasts for the duration of your subscription plus the retention periods in Section 7.</P>
        </Section>

        <Section title="3. Categories of Data and Data Subjects">
          <ul style={{ paddingLeft: 24, display: 'flex', flexDirection: 'column', gap: 10, marginTop: 4 }}>
            <Li><strong>Data subjects:</strong> players participating in your games (typically your employees or event guests).</Li>
            <Li><strong>Personal data:</strong> team names and player display names, game answers and scores, photos and video stills submitted for photo missions, and technical data (IP address, browser type) generated by use of the service.</Li>
            <Li><strong>No special categories</strong> of data are required by the service. You agree not to instruct players to submit sensitive data (e.g. health information) in answers or photos.</Li>
          </ul>
        </Section>

        <Section title="4. Our Obligations as Processor">
          <ul style={{ paddingLeft: 24, display: 'flex', flexDirection: 'column', gap: 10, marginTop: 4 }}>
            <Li>Process player data only to provide the service and on your documented instructions, unless required otherwise by EU or Member State law.</Li>
            <Li>Ensure persons authorised to process the data are bound by confidentiality.</Li>
            <Li>Implement appropriate technical and organisational measures (Article 32): encryption in transit (HTTPS), row-level security and per-tenant isolation in the database, hashed passwords, access controls, and audit-reviewed code.</Li>
            <Li>Assist you, taking into account the nature of the processing, in responding to data subject requests (access, erasure, portability) and in meeting your obligations under Articles 32–36.</Li>
            <Li>Notify you without undue delay after becoming aware of a personal data breach affecting your players&apos; data, with the information reasonably required for your own notification obligations.</Li>
            <Li>Delete or return all player personal data at the end of the provision of services (see Section 7), unless EU or Member State law requires storage.</Li>
            <Li>Make available the information necessary to demonstrate compliance with Article 28 and allow for and contribute to audits conducted by you or an auditor you mandate, upon reasonable written notice and at most once per year, at your expense.</Li>
          </ul>
        </Section>

        <Section title="5. Sub-processors">
          <P>You give general authorisation to the following sub-processors. We will inform account holders of intended changes (via email or in-app notice) at least 30 days in advance, giving you the opportunity to object.</P>
          <ul style={{ paddingLeft: 24, display: 'flex', flexDirection: 'column', gap: 10, marginTop: 12 }}>
            <Li><strong>Supabase Inc.</strong> — database, authentication and file storage (EU-hosted project; some support access from the USA under SCCs).</Li>
            <Li><strong>Vercel Inc.</strong> — application hosting and CDN (USA, SCCs).</Li>
            <Li><strong>Stripe Inc.</strong> — payment processing for your subscription (USA, SCCs; acts primarily as an independent controller for payment data).</Li>
            <Li><strong>Anthropic PBC</strong> — AI features: text entered in the support chat and content submitted to AI photo rating or AI game generation (USA, SCCs).</Li>
            <Li><strong>Resend</strong> — transactional email to account holders (USA, SCCs).</Li>
          </ul>
          <P style={{ marginTop: 16 }}>Each sub-processor is bound by data protection obligations materially equivalent to this DPA. Transfers outside the EU/EEA are protected by the European Commission&apos;s Standard Contractual Clauses and, where applicable, the EU–US Data Privacy Framework.</P>
        </Section>

        <Section title="6. Your Obligations as Controller">
          <P>You are responsible for having a lawful basis for the processing (for workplace events, typically legitimate interest), for informing your players that GameOn is used and where they can read about the processing, and for the content of the missions you create. You warrant that your instructions to us comply with applicable law.</P>
        </Section>

        <Section title="7. Retention and Deletion">
          <ul style={{ paddingLeft: 24, display: 'flex', flexDirection: 'column', gap: 10, marginTop: 4 }}>
            <Li><strong>Player photos:</strong> deleted automatically 30 days after the game ends (enforced by a daily job).</Li>
            <Li><strong>Game data</strong> (teams, scores, answers): retained while your account exists so you can access historical reports.</Li>
            <Li><strong>Account deletion:</strong> the "Delete account" function in the app permanently erases your account and all associated player data. Data export is available via "Export my data".</Li>
          </ul>
        </Section>

        <Section title="8. Liability and Term">
          <P>Liability under this DPA follows the limitation of liability in the Terms of Service. This DPA applies for as long as we process player personal data on your behalf and automatically terminates when all such data has been deleted.</P>
        </Section>

        <Section title="9. Contact">
          <P>Data protection questions and breach notifications: <A href="mailto:hello@playgameon.app">hello@playgameon.app</A>. If your procurement process requires a countersigned copy of this DPA, contact us and we will provide one.</P>
        </Section>

        {/* Footer nav */}
        <div style={{ marginTop: 72, paddingTop: 32, borderTop: '1px solid rgba(124,189,212,0.1)', display: 'flex', gap: 24 }}>
          <Link href="/terms" style={{ fontSize: 14, fontWeight: 600, color: '#8FA8C0', textDecoration: 'none' }}>Terms of Service →</Link>
          <Link href="/privacy" style={{ fontSize: 14, fontWeight: 600, color: '#8FA8C0', textDecoration: 'none' }}>Privacy Policy →</Link>
          <Link href="/" style={{ fontSize: 14, fontWeight: 600, color: '#4A6580', textDecoration: 'none' }}>Back to home</Link>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 48 }}>
      <h2 style={{ fontSize: 20, fontWeight: 800, color: '#DCE4EE', marginBottom: 14, letterSpacing: '-0.02em' }}>{title}</h2>
      {children}
    </section>
  );
}

function P({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return <p style={{ fontSize: 15, lineHeight: 1.75, color: '#8FA8C0', ...style }}>{children}</p>;
}

function Li({ children }: { children: React.ReactNode }) {
  return <li style={{ fontSize: 15, lineHeight: 1.7, color: '#8FA8C0' }}>{children}</li>;
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} style={{ color: '#7CBDD4', textDecoration: 'underline', textUnderlineOffset: 3 }}>{children}</a>;
}
