// scripts/e2e-seed.mjs
//
// Seeds a NON-PRODUCTION Supabase project for the full end-to-end run:
//   - two confirmed admin users (A and B)
//   - a game owned by A with a known game key, set to active
// then signs both in and writes their tokens + the game id to .env.e2e.
//
// Requires (from a disposable test project — never production):
//   TEST_SUPABASE_URL
//   TEST_SUPABASE_ANON_KEY
//   TEST_SUPABASE_SERVICE_ROLE_KEY
//
// Run:  node scripts/e2e-seed.mjs
//
// Safe to re-run: it reuses the test users/game if they already exist.

import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';

const URL = process.env.TEST_SUPABASE_URL;
const ANON = process.env.TEST_SUPABASE_ANON_KEY;
const SERVICE = process.env.TEST_SUPABASE_SERVICE_ROLE_KEY;

if (!URL || !ANON || !SERVICE) {
  console.error(
    'Missing env. Set TEST_SUPABASE_URL, TEST_SUPABASE_ANON_KEY and ' +
      'TEST_SUPABASE_SERVICE_ROLE_KEY (from a disposable test project).'
  );
  process.exit(1);
}

// Guard against pointing this at the production project by accident.
if (/rbkpcnzrimicwzqwvgub/.test(URL)) {
  console.error('Refusing to seed: TEST_SUPABASE_URL points at the production project.');
  process.exit(1);
}

const admin = createClient(URL, SERVICE, { auth: { persistSession: false } });

const PASSWORD = process.env.E2E_TEST_PASSWORD ?? 'E2e-test-Pass-123!';
const GAME_KEY = process.env.E2E_GAME_KEY ?? 'E2ETST';

async function ensureUser(email) {
  // createUser is idempotent enough for our purposes: on "already registered"
  // we fall through and just sign in to recover the id + token.
  const { error } = await admin.auth.admin.createUser({
    email,
    password: PASSWORD,
    email_confirm: true,
  });
  if (error && !/already/i.test(error.message)) {
    throw new Error(`createUser(${email}) failed: ${error.message}`);
  }

  const anon = createClient(URL, ANON, { auth: { persistSession: false } });
  const { data, error: signInErr } = await anon.auth.signInWithPassword({ email, password: PASSWORD });
  if (signInErr || !data.session) {
    throw new Error(`signIn(${email}) failed: ${signInErr?.message ?? 'no session'}`);
  }
  return { id: data.user.id, token: data.session.access_token };
}

async function ensureGame(ownerId) {
  const { data: existing } = await admin
    .from('games')
    .select('id')
    .eq('game_key', GAME_KEY)
    .maybeSingle();
  if (existing) {
    await admin.from('games').update({ user_id: ownerId, status: 'active' }).eq('id', existing.id);
    return existing.id;
  }

  const { data, error } = await admin
    .from('games')
    .insert({
      game_key: GAME_KEY,
      name: 'E2E Test Game',
      user_id: ownerId,
      status: 'active',
      duration_minutes: 60,
      missions: [],
    })
    .select('id')
    .single();
  if (error) throw new Error(`create game failed: ${error.message}`);
  return data.id;
}

const a = await ensureUser('e2e-admin-a@example.com');
const b = await ensureUser('e2e-admin-b@example.com');
const gameId = await ensureGame(a.id);

const lines = [
  `# Generated by scripts/e2e-seed.mjs — do not commit.`,
  `TEST_SUPABASE_URL=${URL}`,
  `TEST_SUPABASE_ANON_KEY=${ANON}`,
  `TEST_SUPABASE_SERVICE_ROLE_KEY=${SERVICE}`,
  `E2E_TOKEN_A=${a.token}`,
  `E2E_TOKEN_B=${b.token}`,
  `E2E_GAME_A_ID=${gameId}`,
  `E2E_GAME_KEY=${GAME_KEY}`,
  '',
].join('\n');

writeFileSync('.env.e2e', lines);
console.log('✓ Seeded test project. Wrote tokens + game id to .env.e2e');
console.log(`  admin A: ${a.id}`);
console.log(`  admin B: ${b.id}`);
console.log(`  game:    ${gameId} (key ${GAME_KEY})`);
